services:
  owncast:
    image: owncast/owncast:latest
    container_name: owncast
    restart: unless-stopped
    ports:
      - "1935:1935"   # RTMP ingest
    volumes:
      - ./data:/app/data   # Persistent data storage

  nginx:
    image: nginx:alpine
    container_name: nginx-owncast
    restart: unless-stopped
    depends_on:
      - owncast
    ports:
      - "1930:1930" # choose port (both)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp