services:  
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=America/New_York
    volumes:
      - ./var/cache/ntfy:/var/cache/ntfy
      - ./etc/ntfy:/etc/ntfy
    ports:
      - 1125:80
    restart: unless-stopped

networks:
  ntfy-network:
    driver: bridge
    
# add the following lines to your other application docker-compose.yml so it can talk to ntfy (remember to remove the #)

#networks:
#  ntfy-network:
#    external: true

# (remember to remove the #)