volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    depends_on:
      - mariadb_freshrss
    environment:
      TZ: Etc/UTC
      DB_TYPE: "mysql"
      DB_HOST: "mariadb_freshrss"
      DB_USER: "______" # provide Username
      DB_PASSWORD: "______" # provide Password
      DB_NAME: "freshrss"
#      CRON_MIN: "25,55" # updates every 25th minute and the 55th minute of every hour
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    logging:
      options:
        max-size: 10m

  mariadb_freshrss:
    image: mariadb:latest
    container_name: mariadb_freshrss
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "_______" # provide Password
      MYSQL_DATABASE: "freshrss"
      MYSQL_USER: "_______" # provide Username
      MYSQL_PASSWORD: "_______" # provide Password
    volumes:
      - ./mariadb:/var/lib/mysql
    command: --innodb-buffer-pool-size=512M --max-connections=200

  nginx:
    image: nginx:alpine
    container_name: nginx-freshrss
    restart: unless-stopped
    depends_on:
      - freshrss
    ports:
      - "5015:5015"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp