---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=____________________  # input private key
      - WIREGUARD_PRESHARED_KEY=____________________  # input preshared key
      - WIREGUARD_ADDRESSES=__.__.__.__/32  # input IPv4 address
      - WIREGUARD_ENDPOINT_PORT=1637  # AirVPN "Entry IP" port (can vary)
      - SERVER_COUNTRIES=United States  # input country 
      - FIREWALL_VPN_INPUT_PORTS=______ # insert forwarded port
    volumes:
      - ./gluetun:/gluetun
    ports:
      - 9091:9091/tcp # transmission port
      - 51413:25045/tcp # airvpn port forwarded (for seeding) ~ must be configured in tranmission client as well.
      - 51413:25045/udp # airvpn port forwarded (for seeding)
      - 6900:3000/tcp # mullvad-browser http port
      - 6901:3001/tcp # mullvad-browser https port
      - 443:443 # nginx-proxy for mullvad-browser https requirement
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --timeout=5 https://1.1.1.1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000 # user id
      - PGID=1000 # group id
      - TZ=Atlanta/New_York
      - USER=______ # insert username (optional but recommended)
      - PASS=______ # insert password (optional but recommended)
    volumes:
       - ./transmission/data:/config
       - ./transmission/watch:/watch
       # add your personal file paths below this line. (remove the # to enable)
#      - /srv/dev-disk-by-uuid-____/downloads:/downloads
#    ports: # (handled by gluetun)   #   DO NOT UNCOMMENT THESE PORTS!
#      - 9091:9091/tcp
#      - 51413:_____/tcp
#      - 51413:_____/udp
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun" # Use gluetun's network
    
---
services:
  mullvad-browser:
    image: lscr.io/linuxserver/mullvad-browser:latest
    container_name: mullvad-browser
    cap_add:
      - NET_ADMIN
    security_opt:
    - seccomp:unconfined #optional
    environment:
      - PUID=1000 # user id
      - PGID=1000 # group id
      - TZ=Etc/UTC # timezone
      - CUSTOM_USER=______   # insert username (optional but recommended)
      - PASSWORD=______   # insert password (optional but recommended)
    volumes:
      - ./mullvad-browser/config:/config
#    ports: # (handled by gluetun)   #   DO NOT UNCOMMENT THIS PORT!
#     - 6900:3000/tcp http port
#     - 6901:3001/tcp https port
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun" # Use gluetun's network

---
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./selkies-certs:/etc/nginx/certs:ro
#    ports: # (handled by gluetun)   #   DO NOT UNCOMMENT THIS PORT!
#      - 443:443
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun" # Use gluetun's network
