services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ./data:/datastore
    environment:   
      - LOGGER_LEVEL=DEBUG       
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub       
      - PLAYWRIGHT_DRIVER_URL=ws://sockpuppetbrowser:3000         # Keep this on port 3000
      - TZ=America/New_York                                       # Change to your timezone
    ports:
      - 5020:5000
    restart: unless-stopped
    depends_on:
      sockpuppetbrowser:
        condition: service_started                                # Ensures Playwright is ready before starting

  sockpuppetbrowser:
    hostname: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser:latest
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    ports:
      - "3000:3000"                                               # Changing port here doesn't work... I've tried
      
    # Setup ntfy network bridge # (so changedetection can talk to ntfy)
#networks:
#  ntfy-network:
#    external: true
    
    # This is an example of how you will send a notification. (use wireguard/tailscale IP)
    # ntfy://100.124.11.69:1125/amazon
    # "amazon" in this example is the subscribed topic on the client. (ntfy app on your external devices)
    
# Additionally to check previous lower prices and to have an additonal way of monitoring I recommend "keepa" application