services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --interval 21600 watchtower brave nginx-brave flame nginx-flame mumble-web nginx-mumbleweb freshrss nginx-freshrss ntfy nginx-ntfy hbbs hbbr vaultwarden nginx-vaultwarden nginx-immich jellyfin nginx-jellyfin jellyseerr nginx-jellyseerr gluetun transmission mullvad-browser nginx-privacy
    # Whitelist: Actively update only these containers & Check every 6 hours
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/New_York

      # Logging
      - WATCHTOWER_LOG_LEVEL=info

      # Email Notifications
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=redacted@gmx.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=redacted@proton.me
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.gmx.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=redacted@gmx.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=redacted_password
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=docker-up

    restart: always
