---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Atlanta/New_York
      - CUSTOM_USER= #optional
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./config:/config
    ports:
      - 8123:8181 # HTTPS for Calibre Manager
      - 8124:8081 # For Calibre Reader Server (setup within Calibre app required)
    restart: unless-stopped
