# docker-compose.yml
# For Nvidia GPUs

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Headless browser for OWUI web loader (Playwright WS server)
  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble
    container_name: playwright
    restart: unless-stopped
    shm_size: "1gb"
    command: npx -y playwright@1.49.1 run-server --browser=chromium --host=0.0.0.0 --port=3000
    expose:
      - "3000"

  # OCR for docs/images via Apache Tika (full image with Tesseract)
  tika:
    image: apache/tika:2.8.0.0-full
    container_name: tika
    restart: unless-stopped
    expose:
      - "9998"

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      - ollama
      - playwright
      - tika
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=duckduckgo
      - WEB_LOADER_ENGINE=playwright
      - PLAYWRIGHT_WS_URL=ws://playwright:3000
      - CONTENT_EXTRACTION_ENGINE=tika
      - TIKA_SERVER_URL=http://tika:9998
    volumes:
      - ./open-webui:/app/backend/data

  nginx:
    image: nginx:alpine
    container_name: nginx-open-webui
    restart: unless-stopped
    depends_on:
      - open-webui
    ports:
      - "7005:7005" # Change to port of choice (both)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    # - C:\Users\username\docker\tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp