[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /opt/printer_data/run/klipper.sock

[file_manager]
enable_object_processing: False
check_klipper_config_path: True

[machine]
provider: none
validate_service: False
validate_config: False

[authorization]
force_logins: false

cors_domains:
  *://localhost
  *://omv.time-puffin.ts.net
  *://omv.time-puffin.ts.net:5006
  *://omv.time-puffin.ts.net:7125
  *://192.168.68.2
  *://192.168.68.2:5006
  *://192.168.68.2:7125
  *://*.ts.net

trusted_clients:
  100.64.0.0/10
  10.0.0.0/8
  127.0.0.0/8
  169.254.0.0/16
  172.16.0.0/12
  192.168.0.0/16
  FE80::/10
  ::1/128

[webcam printercam]
location: printer
enabled: True
service: mjpegstreamer-adaptive
target_fps: 15
target_fps_idle: 5
stream_url: https://omv.time-puffin.ts.net:5006/webcam/?action=stream
snapshot_url: https://omv.time-puffin.ts.net:5006/webcam/?action=snapshot
flip_horizontal: False
flip_vertical: False
rotation: 0
aspect_ratio: 16:9