services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://*machine_name*.tail-scale.ts.net:8901 # INPUT YOUR Tailscale MagicDNS URL - including port # (example displayed)
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true                                         # Change to "false" after sign up
#     - WEB_VAULT_ENABLED=true                                      # web-vault (optional)
#     - WEB_VAULT_FOLDER=web-vault/                                 # web-vault folder
    volumes:
      - ./vw-data:/data
#      - ./bw_web_builds/container_builds/web-vault:/web-vault:ro    # web-vault (optional) ~ (":ro" means read-only)
    
  nginx:
    image: nginx:alpine
    container_name: nginx-vaultwarden
    depends_on:
      - vaultwarden
    restart: unless-stopped
    ports:
      - 8901:443                                                      # Change to your prefered port
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/cert.pem:/etc/ssl/private/fullchain.pem:ro
      - ./certs/key.pem:/etc/ssl/private/privkey.pem:ro
      
# to setup web_vault: https://github.com/dani-garcia/vaultwarden/wiki/Building-binary#install-the-web-vault
# once completed remove # for "web-builds" line and relaunch container.
